import { promises as fs } from 'node:fs';
import { detectShellProfile } from './shared/shell-profile.js';
import { ensureFileExists, escapeRegExp, normalizeTrailingNewlines } from './shared/file-utils.js';

const RELOAD_BLOCK_PREFIX = '# >>> snap-shell-reload:';
const RELOAD_BLOCK_SUFFIX = '# <<< snap-shell-reload:';

const validateAliasName = (value: string): string => {
  const trimmed = value.trim();
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(trimmed)) {
    throw new Error('Alias name must match [A-Za-z_][A-Za-z0-9_]*.');
  }
  return trimmed;
};

const blockStart = (aliasName: string): string => `${RELOAD_BLOCK_PREFIX}${aliasName} >>>`;
const blockEnd = (aliasName: string): string => `${RELOAD_BLOCK_SUFFIX}${aliasName} <<<`;

const removeManagedBlock = (content: string, aliasName: string): string => {
  const start = escapeRegExp(blockStart(aliasName));
  const end = escapeRegExp(blockEnd(aliasName));
  const pattern = new RegExp(`${start}[\\s\\S]*?${end}\\n?`, 'g');
  return content.replace(pattern, '');
};

const aliasExists = (content: string, aliasName: string): boolean => {
  const aliasPattern = new RegExp(`^alias\\s+${escapeRegExp(aliasName)}=`, 'm');
  const functionPattern = new RegExp(`^${escapeRegExp(aliasName)}\\s*\\(\\s*\\)\\s*\\{`, 'm');
  return aliasPattern.test(content) || functionPattern.test(content);
};

const removeAliasDefinition = (content: string, aliasName: string): string => {
  const aliasPattern = new RegExp(`^alias\\s+${escapeRegExp(aliasName)}=[^\\n]*\\n?`, 'gm');
  const functionPattern = new RegExp(`${escapeRegExp(aliasName)}\\s*\\(\\s*\\)\\s*\\{[\\s\\S]*?\\n\\}\\n?`, 'g');
  return content.replace(aliasPattern, '').replace(functionPattern, '');
};

export interface InstallReloadAliasInput {
  aliasName: string;
  overwrite?: boolean;
}

export interface InstallReloadAliasResult {
  ok: boolean;
  profilePath?: string;
  summary?: string;
  details?: string[];
  conflict?: boolean;
  errorMessage?: string;
}

export const installReloadAlias = async (
  input: InstallReloadAliasInput
): Promise<InstallReloadAliasResult> => {
  let aliasName: string;
  try {
    aliasName = validateAliasName(input.aliasName);
  } catch (error) {
    return {
      ok: false,
      errorMessage: error instanceof Error ? error.message : 'Invalid alias name.'
    };
  }

  const overwrite = Boolean(input.overwrite);
  const { profilePath } = await detectShellProfile();
  await ensureFileExists(profilePath);
  const current = await fs.readFile(profilePath, 'utf8');

  if (aliasExists(current, aliasName) && !overwrite) {
    return {
      ok: false,
      conflict: true,
      profilePath,
      errorMessage: `Alias "${aliasName}" already exists.`
    };
  }

  let next = removeManagedBlock(current, aliasName);
  if (overwrite) {
    next = removeAliasDefinition(next, aliasName);
  }

  const timestamp = new Date().toISOString();
  const managedBlock = `${blockStart(aliasName)}
# Generated by alias tool
# Generated: ${timestamp}
alias ${aliasName}="source ${profilePath}"
${blockEnd(aliasName)}
`;

  next = normalizeTrailingNewlines(`${next}\n${managedBlock}`);
  await fs.writeFile(profilePath, next, 'utf8');

  return {
    ok: true,
    profilePath,
    summary: 'Installed shell reload alias.',
    details: [`alias=${aliasName}`, `shell_profile=${profilePath}`]
  };
};
