import { CLAUDE_CODE_ENV_DESCRIPTIONS } from '../claude-code-env-descriptions.js';

export const CLAUDE_PROFILE_LOGIN_ENV_KEYS = ['ANTHROPIC_API_KEY', 'ANTHROPIC_AUTH_TOKEN'] as const;

export const CLAUDE_PROFILE_NON_LOGIN_ENV_KEYS = [
  'ANTHROPIC_BASE_URL',
  'ANTHROPIC_DEFAULT_OPUS_MODEL',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL',
  'ANTHROPIC_DEFAULT_SONNET_MODEL'
] as const;

export const KNOWN_CLAUDE_ENV_KEYS = [
  ...CLAUDE_PROFILE_LOGIN_ENV_KEYS,
  ...CLAUDE_PROFILE_NON_LOGIN_ENV_KEYS
] as const;

// Source: https://code.claude.com/docs/en/settings#environment-variables (retrieved 2026-02-10)
export const KNOWN_CLAUDE_CODE_ENV_KEYS = [
  'ANTHROPIC_API_KEY',
  'ANTHROPIC_AUTH_TOKEN',
  'ANTHROPIC_CUSTOM_HEADERS',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL',
  'ANTHROPIC_DEFAULT_OPUS_MODEL',
  'ANTHROPIC_DEFAULT_SONNET_MODEL',
  'ANTHROPIC_FOUNDRY_API_KEY',
  'ANTHROPIC_FOUNDRY_BASE_URL',
  'ANTHROPIC_FOUNDRY_RESOURCE',
  'ANTHROPIC_MODEL',
  'ANTHROPIC_SMALL_FAST_MODEL',
  'ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION',
  'AWS_BEARER_TOKEN_BEDROCK',
  'BASH_DEFAULT_TIMEOUT_MS',
  'BASH_MAX_OUTPUT_LENGTH',
  'BASH_MAX_TIMEOUT_MS',
  'CLAUDE_AUTOCOMPACT_PCT_OVERRIDE',
  'CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR',
  'CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD',
  'CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS',
  'CLAUDE_CODE_API_KEY_HELPER_TTL_MS',
  'CLAUDE_CODE_CLIENT_CERT',
  'CLAUDE_CODE_CLIENT_KEY_PASSPHRASE',
  'CLAUDE_CODE_CLIENT_KEY',
  'CLAUDE_CODE_EFFORT_LEVEL',
  'CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS',
  'CLAUDE_CODE_DISABLE_AUTO_MEMORY',
  'CLAUDE_CODE_DISABLE_BACKGROUND_TASKS',
  'CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY',
  'CLAUDE_CODE_EXIT_AFTER_STOP_DELAY',
  'CLAUDE_CODE_PROXY_RESOLVES_HOSTS',
  'CLAUDE_CODE_TASK_LIST_ID',
  'CLAUDE_CODE_TEAM_NAME',
  'CLAUDE_CODE_TMPDIR',
  'CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC',
  'CLAUDE_CODE_DISABLE_TERMINAL_TITLE',
  'CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION',
  'CLAUDE_CODE_ENABLE_TASKS',
  'CLAUDE_CODE_ENABLE_TELEMETRY',
  'CLAUDE_CODE_FILE_READ_MAX_OUTPUT_TOKENS',
  'CLAUDE_CODE_HIDE_ACCOUNT_INFO',
  'CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL',
  'CLAUDE_CODE_MAX_OUTPUT_TOKENS',
  'CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS',
  'CLAUDE_CODE_PLAN_MODE_REQUIRED',
  'CLAUDE_CODE_SHELL',
  'CLAUDE_CODE_SHELL_PREFIX',
  'CLAUDE_CODE_SKIP_BEDROCK_AUTH',
  'CLAUDE_CODE_SKIP_FOUNDRY_AUTH',
  'CLAUDE_CODE_SKIP_VERTEX_AUTH',
  'CLAUDE_CODE_SUBAGENT_MODEL',
  'CLAUDE_CODE_USE_BEDROCK',
  'CLAUDE_CODE_USE_FOUNDRY',
  'CLAUDE_CODE_USE_VERTEX',
  'CLAUDE_CONFIG_DIR',
  'CLAUDE_ENV_FILE',
  'CLAUDE_PROJECT_DIR',
  'DISABLE_AUTOUPDATER',
  'DISABLE_BUG_COMMAND',
  'DISABLE_COST_WARNINGS',
  'DISABLE_ERROR_REPORTING',
  'DISABLE_INSTALLATION_CHECKS',
  'DISABLE_NON_ESSENTIAL_MODEL_CALLS',
  'DISABLE_PROMPT_CACHING',
  'DISABLE_PROMPT_CACHING_HAIKU',
  'DISABLE_PROMPT_CACHING_OPUS',
  'DISABLE_PROMPT_CACHING_SONNET',
  'DISABLE_TELEMETRY',
  'ENABLE_TOOL_SEARCH',
  'FORCE_AUTOUPDATE_PLUGINS',
  'HTTP_PROXY',
  'HTTPS_PROXY',
  'IS_DEMO',
  'MAX_MCP_OUTPUT_TOKENS',
  'MAX_THINKING_TOKENS',
  'MCP_CLIENT_SECRET',
  'MCP_OAUTH_CALLBACK_PORT',
  'MCP_TIMEOUT',
  'MCP_TOOL_TIMEOUT',
  'NO_PROXY',
  'OTEL_METRICS_EXPORTER',
  'SLASH_COMMAND_TOOL_CHAR_BUDGET',
  'USE_BUILTIN_RIPGREP',
  'VERTEX_REGION_CLAUDE_3_5_HAIKU',
  'VERTEX_REGION_CLAUDE_3_7_SONNET',
  'VERTEX_REGION_CLAUDE_4_0_OPUS',
  'VERTEX_REGION_CLAUDE_4_0_SONNET',
  'VERTEX_REGION_CLAUDE_4_1_OPUS'
] as const;

const FOCUSED_ENV_SET = new Set<string>(KNOWN_CLAUDE_ENV_KEYS);

export const KNOWN_CLAUDE_CODE_OTHER_ENV_KEYS = KNOWN_CLAUDE_CODE_ENV_KEYS.filter(
  (name) => !FOCUSED_ENV_SET.has(name)
);

export const KNOWN_CLAUDE_CODE_OTHER_ENV_WITH_DESCRIPTIONS = KNOWN_CLAUDE_CODE_OTHER_ENV_KEYS.map(
  (key) => ({
    key,
    description: CLAUDE_CODE_ENV_DESCRIPTIONS[key] ?? 'No description available in docs.'
  })
);

export const buildOtherEnvVariableHelper = (): string =>
  [
    'Known Claude Code env vars (Other):',
    ...KNOWN_CLAUDE_CODE_OTHER_ENV_WITH_DESCRIPTIONS.map(({ key, description }) => `${key}: ${description}`),
    'Use --ENV_NAME=value.',
    'Unknown uppercase env keys are also supported.'
  ].join('\n');
